### ISSUE TITLE
sometimes invalid

### ISSUE THREAD

**Issue by Tanson** [sgofferj/Ardupilot-Neopixel#1]
why is the code sometimes invalid, pixhawk led still on.

**Comment by sgofferj** [comment]
Please describe exactly what your problem is.

**Comment by Tanson** [comment]
I have been connected to the Pixhawk's I2C port. Sometimes plug in the battery arduino can replace the pixhawk led, sometimes plug in the battery Pixhawk led still lit, arduino can not receive the message
